### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MemerGamer** [AniMathIO/AniMathIO#15]
# General improvements
Bug fixes:
- [ ] #11 

Ongoing improvements:
- [x] #3 

# For v1.7.0
Features
- [ ] Implement Manim -> AniMathIO translation layer
- [ ] Mathematical animations using mafs animations (which is still in development)
- [ ] replace fabric.js with [https://konvajs.org/](https://konvajs.org/)

Enchantments
- [ ] Improve animations
- [ ] refactor state class into smaller subclasses

<details>
<summary><h1>For v1.6.0</h1></summary>
<b>Features:</b>
<ul>
<li>make sure gemini model is selectable when adding access token</li>
<li>Create flatpak build</li>
<li>#79</li>
<li><s>create aur build</s> <a href="https://aur.archlinux.org/packages/animathio-bin">done</a> by <a href="https://aur.archlinux.org/account/zxp19821005">zxp19821005</a></li>
</ul>
<b>Enchantments:</b>
<ul>
<li>#99</li>
</ul>
</details>

<details>
<summary><h1>For v1.5.0</h1></summary>
<b>Features:</b>
<ul>
<li>#92</li>
</ul>
<b>Enchantments:</b>
<ul>
<li>#90</li>
</ul>
</details>

<details>
<summary><h1>For v1.4.1</h1></summary>
<b>Enchantments:</b>
<ul>
<li>Created <a href="https://docs.animathio.com/">documentation website</a> with <a href="https://docusaurus.io/">Docosaurus</a></li>
</ul>
<b>Fixes:</b>
<ul>
<li>#84</li>
</ul>
</details>

<details>
<summary><h1>For v1.4.0</h1></summary>
<b>Features:</b>
<ul>
<li>#5</li>
<li>#69</li>
</ul>
<b>Fixes:</b>
<ul>
<li>#73</li>
</ul>
</details>

<details>
<summary><h1>For v1.3.1</h1></summary>
<b>Features:</b>
<ul>
<li>#63</li>
<li>#50</li>
<li>#57</li>
<li>#61</li>
<li>#59</li>
</ul>
<b>Fixes:</b>
<ul>
<li>#71</li>
</ul>
</details>

<details>
<summary><h1>For v1.2.0</h1></summary>
<b>Features:</b>
<ul>
<li>#9</li>
<li>#40 <s>#20</s> - solved the source of the problem as well</li>
<li>#6</li>
<li>#43</li>
</ul>
</details>

<details>
<summary><h1>For v1.1.0</h1></summary>
<b>Features:</b>
<ul>
<li>test version number bump up with release-please</li>
</ul>
<b>Enchantments:</b>
<ul>
<li>fix configurations for electron builds</li>
</ul>
</details>

<details>
<summary><h1>For v1.0.0</h1></summary>
<b>Features:</b>
<ul>
<li>#1</li>
<li>#16</li>
<li>#2</li>
<li>#21</li>
<li>#34</li>
</ul>
<b>Enchantments:</b>
<ul>
<li>#4</li>
<li>#14</li>
</ul>
</details>
